module.exports = {
	development:{
		mongo:'mongodb://localhost',
		db:{
			host:'localhost',
			db:process.env.USER,
			user:process.env.USER,
			port:5432,
			password:''
		}
	},
	test:{
		db:{
			host:'localhost',
			db:'travis_ci_test',
			user:'postgres',
			password:''
		}
	}
}